import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Head from 'next/head'
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
  const fontPath = `${basePath}/fonts/DS-DIGIT.TTF`;

  return (
    <html lang="en">
      <Head>
        <style>
          {`
            @font-face {
              font-family: 'DS-DIGIT';
              src: url('${fontPath}') format('truetype');
              font-weight: normal;
              font-style: normal;
            }
          `}
        </style>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
