import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '../styles/globals.css'
import FontLoader from '@/components/FontLoader'
// import './globals.css'
// import { GoogleAnalytics } from '@next/third-parties/google'
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { WebVitals } from "./web-vitals";
import { RegisterSW } from '@/components/RegisterSW';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <FontLoader />
      </head>
      <body className={''}>
        <RegisterSW />
        <WebVitals />
        <Theme appearance={'dark'}>
        {children}
        {/* <ThemePanel /> */}
        </Theme>
        {/* <GoogleAnalytics gaId={'G-ZL1YVF18VG'} /> */}
      </body>
    </html>
  )
}
