import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import FontLoader from '@/components/FontLoader'
// import './globals.css'
import { GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <FontLoader />
      </head>
      <body className={inter.className}>
        {children}
        <GoogleAnalytics gaId={'G-ZL1YVF18VG'} />
      </body>
    </html>
  )
}
