name: Next.js Tests
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test:ci
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      # serve 会自动在端口 3000 启动一个静态服务器来服务 out 目录。
      - run: npx serve@latest out &
      - run: npx wait-on http://localhost:3000
      - run: npm run cypress:run
      # - run: npm run test:e2e:prod
      # # &关键符号，表示后台运行这个命令，不会阻塞进程，可继续执行后续命令
      # - run: npm run start &
      # # 等待某个资源变(如URL、端口、文件)为可用状态
      # - run: npx wait-on http://localhost:3000
      # - run: npm run cypress:run